/*
 * DuckTinyCC embedded TinyCC runtime extraction.
 *
 * Included by tcc_module.c.  The generated byte manifests are process-global and extracted
 * lazily into a content-hash-keyed temp directory for tcc_set_lib_path().
 */

#ifndef DUCKTINYCC_WASM_UNSUPPORTED
/*
 * Embedded TinyCC runtime support (generated by cmake/gen_embedded_runtime.cmake).
 *
 * The cmake build embeds libtcc1.a and all TinyCC include headers as static byte arrays
 * directly in the extension binary so that no external runtime files are required at
 * deployment.  On first use, tcc_ensure_embedded_runtime() extracts these blobs to a
 * deterministic temp directory (keyed by a hash of libtcc1.a) and returns that path.
 * Subsequent calls in the same process (or across processes for the same build) reuse
 * the already-extracted directory without re-writing files.
 *
 * The extracted layout mirrors what tcc_configure_runtime_paths() expects:
 *   {dir}/libtcc1.a      -- the TinyCC relocatable helper archive
 *   {dir}/include/       -- TinyCC's own headers (stdarg.h, stddef.h, tccdefs.h, etc.)
 *
 * TinyCC's {B}/include sysinclude expansion (CONFIG_TCC_SYSINCLUDEPATHS) is satisfied
 * when tcc_set_lib_path(s, dir) is called, because {B} expands to tcc_lib_path which
 * we set to `dir`.  System headers remain searchable via standard OS paths; only the
 * TinyCC-specific headers are overridden by the embedded copies.
 */

/* Forward declarations of symbols defined in embedded_runtime.c (generated at build time). */
typedef struct {
	const char *name;
	const unsigned char *data;
	size_t size;
} ducktinycc_embedded_header_entry_t;

extern const unsigned char ducktinycc_embedded_libtcc1[];
extern const size_t ducktinycc_embedded_libtcc1_size;
extern const ducktinycc_embedded_header_entry_t ducktinycc_embedded_headers[];
extern const size_t ducktinycc_embedded_headers_count;

/* Process-global extraction state. */
static char g_embedded_runtime_dir[1024] = {0};
static atomic_flag g_embedded_runtime_lock = ATOMIC_FLAG_INIT;
static bool g_embedded_runtime_extracted = false;

/* FNV-1a 32-bit hash for naming the extraction directory. */
static unsigned int tcc_fnv1a_hash(unsigned int hash, const unsigned char *data, size_t len) {
	size_t i;
	for (i = 0; i < len; i++) {
		hash ^= (unsigned int)data[i];
		hash *= 16777619u;
	}
	return hash;
}

/* Write `size` bytes from `data` to `path`.  Returns true on success. */
static bool tcc_write_file_bytes(const char *path, const unsigned char *data, size_t size) {
	FILE *f = fopen(path, "wb");
	int ok;
	if (!f) {
		return false;
	}
	ok = (fwrite(data, 1, size, f) == size);
	fclose(f);
	return ok != 0;
}

/* tcc_mkdirs_for_relpath: Creates all intermediate directories under base_dir that are
 * implied by the forward-slash relpath (e.g. relpath="include/winapi/windows.h" creates
 * base_dir/include/ then base_dir/include/winapi/).  Individual mkdir failures are
 * silently ignored (EEXIST is expected on the reuse path).  Win32 accepts forward
 * slashes in path operations, so we use them uniformly here. */
static void tcc_mkdirs_for_relpath(const char *base_dir, const char *relpath) {
	char rel[512];
	char path[1400];
	char *p;
	size_t base_len;
	bool base_has_sep;
	size_t prefix_len;
	strncpy(rel, relpath, sizeof(rel) - 1);
	rel[sizeof(rel) - 1] = '\0';
	base_len = strlen(base_dir);
	base_has_sep = base_len > 0 && (base_dir[base_len - 1] == '/' || base_dir[base_len - 1] == '\\');
	prefix_len = base_len + (base_has_sep ? 0 : 1);
	if (prefix_len + 1 >= sizeof(path)) {
		return;
	}
	memcpy(path, base_dir, base_len);
	if (!base_has_sep) {
		path[base_len] = '/';
	}
	p = rel;
	while ((p = strchr(p, '/')) != NULL) {
		size_t rel_len;
		*p = '\0'; /* temporarily null-terminate at this slash */
		rel_len = strlen(rel);
		if (prefix_len + rel_len + 1 < sizeof(path)) {
			memcpy(path + prefix_len, rel, rel_len);
			path[prefix_len + rel_len] = '\0';
			(void)TCC_MKDIR(path); /* ignore result; EEXIST is normal on reuse */
		}
		*p = '/';              /* restore */
		p++;
	}
}

#ifdef _WIN32
/* tcc_generate_ucrt_msvcrt_def: Best-effort generation of UCRT-correct msvcrt.def.
 *
 * Why: TinyCC on PE links against "c" by resolving msvcrt.def from {B}/lib first.
 * The static msvcrt.def shipped in upstream TinyCC targets legacy MSVCRT and can
 * cause allocator mismatch when the host process is UCRT (Rtools 4.2+ / UCRT64).
 *
 * Strategy: if a `tcc.exe` is available (next to runtime dir or on PATH), run:
 *   tcc.exe -impdef <SystemRoot>\System32\ucrtbase.dll -o <runtime>/lib/msvcrt.def
 *
 * This mirrors the proven Rtinycc approach and avoids direct linkage to internal
 * TinyCC tcctools symbols (which are not guaranteed to be exported in libtcc.a).
 *
 * Non-fatal: if generation fails we keep whatever msvcrt.def is present.
 */
static bool tcc_generate_ucrt_msvcrt_def(const char *runtime_dir) {
	char tcc_exe[900];
	char dll_path[768];
	char out_def[900];
	char cmd[2600];
	const char *system_root;
	int rc;

	if (!runtime_dir || runtime_dir[0] == '\0') {
		return false;
	}

	/* Prefer runtime-local tcc.exe, then PATH fallback. */
	snprintf(tcc_exe, sizeof(tcc_exe), "%s/tcc.exe", runtime_dir);
	if (!tcc_path_exists(tcc_exe)) {
		snprintf(tcc_exe, sizeof(tcc_exe), "%s/bin/tcc.exe", runtime_dir);
		if (!tcc_path_exists(tcc_exe)) {
			snprintf(tcc_exe, sizeof(tcc_exe), "tcc.exe");
		}
	}

	system_root = getenv("SystemRoot");
	if (system_root && system_root[0] != '\0') {
		snprintf(dll_path, sizeof(dll_path), "%s\\System32\\ucrtbase.dll", system_root);
	} else {
		snprintf(dll_path, sizeof(dll_path), "C:\\Windows\\System32\\ucrtbase.dll");
	}
	if (!tcc_path_exists(dll_path)) {
		return false;
	}

	tcc_mkdirs_for_relpath(runtime_dir, "lib/msvcrt.def");
	snprintf(out_def, sizeof(out_def), "%s/lib/msvcrt.def", runtime_dir);

	snprintf(cmd, sizeof(cmd), "\"%s\" -impdef \"%s\" -o \"%s\"", tcc_exe, dll_path, out_def);
	rc = system(cmd);

	return rc == 0 && tcc_path_exists(out_def);
}
#endif

/* tcc_ensure_embedded_runtime: Extracts the embedded libtcc1.a and TinyCC runtime assets
 * to a temp directory on first call.  Returns a stable pointer to the directory path string,
 * or NULL if extraction failed (extension will still attempt to use the compile-time path).
 * Thread-safe via atomic spinlock; content-hash-keyed directory allows cross-process reuse.
 *
 * Manifest entry name fields are forward-slash relpaths from the extraction root,
 * e.g. "include/stdarg.h", "include/winapi/windows.h", "lib/kernel32.def".
 * Intermediate directories are created on demand by tcc_mkdirs_for_relpath(). */
static const char *tcc_ensure_embedded_runtime(void) {
	char tmp_base[512];
	char dir_path[768];
	char libtcc1_path[800]; /* dir_path + "/libtcc1.a" */
	unsigned int hash;
	size_t i;
	const char *tmpdir;

	/* Fast path: already extracted this process. */
	if (g_embedded_runtime_extracted) {
		return g_embedded_runtime_dir[0] ? g_embedded_runtime_dir : NULL;
	}

	/* Acquire spinlock. */
	while (atomic_flag_test_and_set_explicit(&g_embedded_runtime_lock, memory_order_acquire)) {}

	/* Double-checked locking. */
	if (g_embedded_runtime_extracted) {
		atomic_flag_clear_explicit(&g_embedded_runtime_lock, memory_order_release);
		return g_embedded_runtime_dir[0] ? g_embedded_runtime_dir : NULL;
	}

	/* Determine system temp directory. */
#ifdef _WIN32
	tmpdir = getenv("TEMP");
	if (!tmpdir || tmpdir[0] == '\0') tmpdir = getenv("TMP");
	if (!tmpdir || tmpdir[0] == '\0') tmpdir = "C:\\Temp";
#else
	tmpdir = getenv("TMPDIR");
	if (!tmpdir || tmpdir[0] == '\0') tmpdir = "/tmp";
#endif
	strncpy(tmp_base, tmpdir, sizeof(tmp_base) - 1);
	tmp_base[sizeof(tmp_base) - 1] = '\0';

	/* Hash libtcc1.a and embedded assets to produce a stable, unique directory name. */
	hash = tcc_fnv1a_hash(2166136261u, ducktinycc_embedded_libtcc1, ducktinycc_embedded_libtcc1_size);
	for (i = 0; i < ducktinycc_embedded_headers_count; i++) {
		hash = tcc_fnv1a_hash(hash, (const unsigned char *)ducktinycc_embedded_headers[i].name, strlen(ducktinycc_embedded_headers[i].name));
		hash = tcc_fnv1a_hash(hash, ducktinycc_embedded_headers[i].data, ducktinycc_embedded_headers[i].size);
	}
#ifdef _WIN32
	snprintf(dir_path, sizeof(dir_path), "%s\\ducktinycc_%08x", tmp_base, hash);
	snprintf(libtcc1_path, sizeof(libtcc1_path), "%s\\libtcc1.a", dir_path);
#else
	snprintf(dir_path, sizeof(dir_path), "%s/ducktinycc_%08x", tmp_base, hash);
	snprintf(libtcc1_path, sizeof(libtcc1_path), "%s/libtcc1.a", dir_path);
#endif

	/* If libtcc1.a already present, the dir is valid; reuse it. */
	if (!tcc_path_exists(libtcc1_path)) {
		/* Create root extraction dir. */
		if (!TCC_MKDIR(dir_path)) {
			g_embedded_runtime_extracted = true;
			atomic_flag_clear_explicit(&g_embedded_runtime_lock, memory_order_release);
			return NULL;
		}
		/* Write libtcc1.a. */
		if (!tcc_write_file_bytes(libtcc1_path,
		                          ducktinycc_embedded_libtcc1,
		                          ducktinycc_embedded_libtcc1_size)) {
			g_embedded_runtime_extracted = true;
			atomic_flag_clear_explicit(&g_embedded_runtime_lock, memory_order_release);
			return NULL;
		}
		/* Write each embedded asset.
		 * entry.name is a forward-slash relpath from the extraction root, e.g.
		 *   "include/stdarg.h"           (non-Windows TinyCC internal headers)
		 *   "include/winapi/windows.h"   (Windows API headers)
		 *   "lib/kernel32.def"           (Windows import library definitions)
		 * tcc_mkdirs_for_relpath creates any needed intermediate directories. */
		for (i = 0; i < ducktinycc_embedded_headers_count; i++) {
			char asset_path[900];
			tcc_mkdirs_for_relpath(dir_path, ducktinycc_embedded_headers[i].name);
			snprintf(asset_path, sizeof(asset_path), "%s/%s",
			         dir_path, ducktinycc_embedded_headers[i].name);
			/* Non-fatal: if an asset fails to write, continue; TinyCC may fall
			 * back to a system copy.  libtcc1.a is the critical artifact. */
			(void)tcc_write_file_bytes(asset_path,
			                           ducktinycc_embedded_headers[i].data,
			                           ducktinycc_embedded_headers[i].size);
		}
	}

#ifdef _WIN32
	/* Keep CRT import definition aligned with local UCRT runtime. */
	(void)tcc_generate_ucrt_msvcrt_def(dir_path);
#endif

	strncpy(g_embedded_runtime_dir, dir_path, sizeof(g_embedded_runtime_dir) - 1);
	g_embedded_runtime_dir[sizeof(g_embedded_runtime_dir) - 1] = '\0';
	g_embedded_runtime_extracted = true;

	atomic_flag_clear_explicit(&g_embedded_runtime_lock, memory_order_release);
	return g_embedded_runtime_dir;
}
#endif /* !DUCKTINYCC_WASM_UNSUPPORTED */

