# cmake/gen_embedded_runtime.cmake
#
# Generates src/embedded_runtime.c containing:
#   - ducktinycc_embedded_libtcc1[]   : libtcc1.a binary blob (platform-specific, built at compile time)
#   - ducktinycc_embedded_headers[]   : all TinyCC include headers as {name, content} pairs
#
# The extension extracts these to a temp directory at first use so TinyCC can find its runtime
# entirely from the extension binary itself (no external runtime files required at deployment).
#
# Invocation (via CMake custom command):
#   cmake -D LIBTCC1_PATH=<path/to/libtcc1.a>
#         -D HEADERS_DIR=<path/to/tinycc/include>
#         -D OUTPUT_FILE=<path/to/embedded_runtime.c>
#         -P cmake/gen_embedded_runtime.cmake

cmake_minimum_required(VERSION 3.5)

foreach(required_var LIBTCC1_PATH HEADERS_DIR OUTPUT_FILE)
    if(NOT DEFINED ${required_var})
        message(FATAL_ERROR "gen_embedded_runtime.cmake: ${required_var} is required")
    endif()
endforeach()

# ---- helpers ----------------------------------------------------------------

# Write a binary file as a named C unsigned char array + size constant.
# Appends the declaration lines to the file at OUTPUT_FILE.
function(append_binary_blob_as_c_array INPUT_PATH SYMBOL_NAME)
    if(NOT EXISTS "${INPUT_PATH}")
        message(FATAL_ERROR "gen_embedded_runtime.cmake: file not found: ${INPUT_PATH}")
    endif()
    file(READ "${INPUT_PATH}" hex_data HEX)
    string(LENGTH "${hex_data}" hex_len)
    math(EXPR byte_count "${hex_len} / 2")

    # Convert "aabbcc..." -> "0xaa,0xbb,0xcc,..."
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex_csv "${hex_data}")

    # Chunk into lines of 16 bytes each (32 hex chars + commas) for readability
    # CMake regex can't do fixed-width chunking cleanly, so we emit a single long
    # initializer wrapped at the outer braces. Compilers handle this fine.
    file(APPEND "${OUTPUT_FILE}"
        "/* ${INPUT_PATH} */\n"
        "const unsigned char ${SYMBOL_NAME}[] = {\n"
        "${hex_csv}\n"
        "};\n"
        "const size_t ${SYMBOL_NAME}_size = ${byte_count};\n\n"
    )
endfunction()

# Write a text file as a named C string literal (hex-encoded to avoid escaping).
# Emits:  static const unsigned char <sym>_bytes[] = {...};
# The runtime writes these bytes directly to disk (preserving any platform line endings).
function(append_text_file_as_c_array INPUT_PATH SYMBOL_NAME)
    if(NOT EXISTS "${INPUT_PATH}")
        message(FATAL_ERROR "gen_embedded_runtime.cmake: file not found: ${INPUT_PATH}")
    endif()
    file(READ "${INPUT_PATH}" hex_data HEX)
    string(LENGTH "${hex_data}" hex_len)
    math(EXPR byte_count "${hex_len} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex_csv "${hex_data}")
    file(APPEND "${OUTPUT_FILE}"
        "static const unsigned char ${SYMBOL_NAME}_bytes[] = {\n"
        "${hex_csv}\n"
        "};\n"
        "static const size_t ${SYMBOL_NAME}_size = ${byte_count};\n\n"
    )
endfunction()

# ---- collect header files ---------------------------------------------------

file(GLOB header_files "${HEADERS_DIR}/*.h")
list(SORT header_files)  # deterministic order

# ---- write output file ------------------------------------------------------

# Overwrite (not append) at the start
file(WRITE "${OUTPUT_FILE}"
    "/* Auto-generated by cmake/gen_embedded_runtime.cmake - do not edit.\n"
    " * Contains libtcc1.a and TinyCC include headers embedded as byte arrays.\n"
    " * Extracted to a temp directory at runtime by tcc_ensure_embedded_runtime().\n"
    " */\n"
    "#include <stddef.h>\n\n"
)

# 1. libtcc1.a binary blob
append_binary_blob_as_c_array("${LIBTCC1_PATH}" "ducktinycc_embedded_libtcc1")

# 2. Each header file as a static byte array (prefixed by filename for the table)
set(header_syms "")
foreach(hdr_path ${header_files})
    get_filename_component(hdr_name "${hdr_path}" NAME)
    # Turn "stdarg.h" -> "ducktinycc_hdr_stdarg_h"
    string(REPLACE "." "_" sym_suffix "${hdr_name}")
    set(sym "ducktinycc_hdr_${sym_suffix}")
    list(APPEND header_syms "${sym}")
    list(APPEND header_names "${hdr_name}")
    append_text_file_as_c_array("${hdr_path}" "${sym}")
endforeach()

# 3. Manifest table: {name, data, size} entries terminated by a NULL entry
file(APPEND "${OUTPUT_FILE}"
    "typedef struct {\n"
    "    const char *name;\n"
    "    const unsigned char *data;\n"
    "    size_t size;\n"
    "} ducktinycc_embedded_header_entry_t;\n\n"
    "const ducktinycc_embedded_header_entry_t ducktinycc_embedded_headers[] = {\n"
)

list(LENGTH header_syms n_headers)
math(EXPR last_idx "${n_headers} - 1")
set(idx 0)
foreach(sym ${header_syms})
    list(GET header_names ${idx} hdr_name)
    file(APPEND "${OUTPUT_FILE}"
        "    { \"${hdr_name}\", ${sym}_bytes, (size_t)sizeof(${sym}_bytes) },\n"
    )
    math(EXPR idx "${idx} + 1")
endforeach()

file(APPEND "${OUTPUT_FILE}"
    "    { (const char *)0, (const unsigned char *)0, 0 }\n"
    "};\n"
    "const size_t ducktinycc_embedded_headers_count = ${n_headers};\n"
)

message(STATUS "gen_embedded_runtime: wrote ${OUTPUT_FILE} (${n_headers} headers + libtcc1.a)")
