/*
 * DuckTinyCC generated-UDF ABI prelude.
 *
 * This string is prepended to TinyCC wrapper compilation units.  Keep it C99/TinyCC-friendly:
 * no host-only headers except <stdint.h>, no DuckDB headers, and no allocator ownership changes.
 * Descriptor structs are borrowed views over DuckDB vectors; generated wrappers must not free them
 * or retain them after the call returns.
 */

#pragma once

static const char ducktinycc_udf_abi_prelude[] =
    "#include <stdint.h>\n"
    "/* Composite descriptors below are borrowed views from DuckDB vectors. */\n"
    "/* Wrappers must not free them and must not retain them after invocation. */\n"
    "typedef struct {\n"
    "  uint64_t lower;\n"
    "  int64_t upper;\n"
    "} ducktinycc_hugeint_t;\n"
    "typedef struct {\n"
    "  const void *ptr;\n"
    "  uint64_t len;\n"
    "} ducktinycc_blob_t;\n"
    "typedef struct {\n"
    "  int32_t days;\n"
    "} ducktinycc_date_t;\n"
    "typedef struct {\n"
    "  int64_t micros;\n"
    "} ducktinycc_time_t;\n"
    "typedef struct {\n"
    "  int64_t micros;\n"
    "} ducktinycc_timestamp_t;\n"
    "typedef struct {\n"
    "  int32_t months;\n"
    "  int32_t days;\n"
    "  int64_t micros;\n"
    "} ducktinycc_interval_t;\n"
    "typedef struct {\n"
    "  uint8_t width;\n"
    "  uint8_t scale;\n"
    "  ducktinycc_hugeint_t value;\n"
    "} ducktinycc_decimal_t;\n"
    "typedef struct {\n"
    "  const void *ptr;\n"
    "  const uint64_t *validity;\n"
    "  uint64_t offset;\n"
    "  uint64_t len;\n"
    "} ducktinycc_list_t;\n"
    "typedef struct {\n"
    "  const void *ptr;\n"
    "  const uint64_t *validity;\n"
    "  uint64_t offset;\n"
    "  uint64_t len;\n"
    "} ducktinycc_array_t;\n"
    "typedef struct {\n"
    "  const void *const *field_ptrs;\n"
    "  const uint64_t *const *field_validity;\n"
    "  uint64_t field_count;\n"
    "  uint64_t offset;\n"
    "} ducktinycc_struct_t;\n"
    "typedef struct {\n"
    "  const void *key_ptr;\n"
    "  const uint64_t *key_validity;\n"
    "  const void *value_ptr;\n"
    "  const uint64_t *value_validity;\n"
    "  uint64_t offset;\n"
    "  uint64_t len;\n"
    "} ducktinycc_map_t;\n"
    "typedef struct {\n"
    "  const uint8_t *tag_ptr;\n"
    "  const void *const *member_ptrs;\n"
    "  const uint64_t *const *member_validity;\n"
    "  uint64_t member_count;\n"
    "  uint64_t offset;\n"
    "} ducktinycc_union_t;\n"
    "/* Accessor helpers below operate on caller-owned memory spans. */\n"
    "extern int ducktinycc_valid_is_set(const uint64_t *validity, uint64_t idx);\n"
    "extern void ducktinycc_valid_set(uint64_t *validity, uint64_t idx, int valid);\n"
    "extern int ducktinycc_span_contains(uint64_t len, uint64_t idx);\n"
    "extern const void *ducktinycc_ptr_add(const void *base, uint64_t byte_offset);\n"
    "extern void *ducktinycc_ptr_add_mut(void *base, uint64_t byte_offset);\n"
    "extern int ducktinycc_span_fits(uint64_t len, uint64_t offset, uint64_t width);\n"
    "extern const void *ducktinycc_buf_ptr_at(const void *base, uint64_t len, uint64_t offset, uint64_t width);\n"
    "extern void *ducktinycc_buf_ptr_at_mut(void *base, uint64_t len, uint64_t offset, uint64_t width);\n"
    "extern int ducktinycc_read_bytes(const void *base, uint64_t len, uint64_t offset, void *out, uint64_t width);\n"
    "extern int ducktinycc_write_bytes(void *base, uint64_t len, uint64_t offset, const void *in, uint64_t width);\n"
    "extern int ducktinycc_read_i8(const void *base, uint64_t len, uint64_t offset, int8_t *out);\n"
    "extern int ducktinycc_write_i8(void *base, uint64_t len, uint64_t offset, int8_t value);\n"
    "extern int ducktinycc_read_u8(const void *base, uint64_t len, uint64_t offset, uint8_t *out);\n"
    "extern int ducktinycc_write_u8(void *base, uint64_t len, uint64_t offset, uint8_t value);\n"
    "extern int ducktinycc_read_i16(const void *base, uint64_t len, uint64_t offset, int16_t *out);\n"
    "extern int ducktinycc_write_i16(void *base, uint64_t len, uint64_t offset, int16_t value);\n"
    "extern int ducktinycc_read_u16(const void *base, uint64_t len, uint64_t offset, uint16_t *out);\n"
    "extern int ducktinycc_write_u16(void *base, uint64_t len, uint64_t offset, uint16_t value);\n"
    "extern int ducktinycc_read_i32(const void *base, uint64_t len, uint64_t offset, int32_t *out);\n"
    "extern int ducktinycc_write_i32(void *base, uint64_t len, uint64_t offset, int32_t value);\n"
    "extern int ducktinycc_read_u32(const void *base, uint64_t len, uint64_t offset, uint32_t *out);\n"
    "extern int ducktinycc_write_u32(void *base, uint64_t len, uint64_t offset, uint32_t value);\n"
    "extern int ducktinycc_read_i64(const void *base, uint64_t len, uint64_t offset, int64_t *out);\n"
    "extern int ducktinycc_write_i64(void *base, uint64_t len, uint64_t offset, int64_t value);\n"
    "extern int ducktinycc_read_u64(const void *base, uint64_t len, uint64_t offset, uint64_t *out);\n"
    "extern int ducktinycc_write_u64(void *base, uint64_t len, uint64_t offset, uint64_t value);\n"
    "extern int ducktinycc_read_f32(const void *base, uint64_t len, uint64_t offset, float *out);\n"
    "extern int ducktinycc_write_f32(void *base, uint64_t len, uint64_t offset, float value);\n"
    "extern int ducktinycc_read_f64(const void *base, uint64_t len, uint64_t offset, double *out);\n"
    "extern int ducktinycc_write_f64(void *base, uint64_t len, uint64_t offset, double value);\n"
    "extern int ducktinycc_read_ptr(const void *base, uint64_t len, uint64_t offset, const void **out);\n"
    "extern int ducktinycc_write_ptr(void *base, uint64_t len, uint64_t offset, const void *value);\n"
    "extern int ducktinycc_list_is_valid(const ducktinycc_list_t *list, uint64_t idx);\n"
    "extern const void *ducktinycc_list_elem_ptr(const ducktinycc_list_t *list, uint64_t idx, uint64_t elem_size);\n"
    "extern int ducktinycc_array_is_valid(const ducktinycc_array_t *arr, uint64_t idx);\n"
    "extern const void *ducktinycc_array_elem_ptr(const ducktinycc_array_t *arr, uint64_t idx, uint64_t elem_size);\n"
    "extern const void *ducktinycc_struct_field_ptr(const ducktinycc_struct_t *st, uint64_t idx);\n"
    "extern int ducktinycc_struct_field_is_valid(const ducktinycc_struct_t *st, uint64_t field_idx);\n"
    "extern const void *ducktinycc_map_key_ptr(const ducktinycc_map_t *m, uint64_t idx, uint64_t key_size);\n"
    "extern const void *ducktinycc_map_value_ptr(const ducktinycc_map_t *m, uint64_t idx, uint64_t value_size);\n"
    "extern int ducktinycc_map_key_is_valid(const ducktinycc_map_t *m, uint64_t idx);\n"
    "extern int ducktinycc_map_value_is_valid(const ducktinycc_map_t *m, uint64_t idx);\n"
    "extern int ducktinycc_union_tag(const ducktinycc_union_t *u);\n"
    "extern const void *ducktinycc_union_member_ptr(const ducktinycc_union_t *u, uint64_t member_idx);\n"
    "extern int ducktinycc_union_member_is_valid(const ducktinycc_union_t *u, uint64_t member_idx);\n"
    "extern int duckdb_validity_row_is_valid(uint64_t *validity, uint64_t row);\n";
